services:
  vpn:
    image: bubuntux/nordlynx:latest # bubuntux/nordbpn:latest to get key
    container_name: vpn
#    dns:
#      - 1.1.1.1 # don't think it's necessary
#      - 8.8.8.8
#    network_mode: bridge # THIS SHOULDNT BE THERE. THEN I CANT DNS ROUTE???
    networks:
      - discovery
    cap_add:
      - NET_ADMIN               # Required
      - SYS_MODULE              # Required for TECHNOLOGY=NordLynx
    sysctls:
      - net.ipv4.conf.all.rp_filter=2
    devices:
      - /dev/net/tun            # Required
    environment:                # Review https://github.com/bubuntux/nordvpn#environment-variables
      - PRIVATE_KEY=${PRIVATE_KEY}
     # to get  key
     #  - TOKEN=${NORDVPN_TOKEN}
     #  - CONNECT=Sweden
     #  - TECHNOLOGY=NordLynx
     #  - CYBER_SEC=Enable
     #  - NETWORK=192.168.1.0/24
     #  - TZ=Europe/Copenhagen
     #  - DEBUG=on
    env_file:
      - .env
    ports:
      - "7503:7503" # qbittorrent webui

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    network_mode: service:vpn
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
      - UMASK_SET=022
      - WEBUI_PORT=7503
    volumes:
      - /mnt/storage/config/torrent:/config
      - /mnt/storage/downloads:/downloads
    restart: unless-stopped
    depends_on:
      - vpn
    labels:
      - traefik.enable=true
      - traefik.http.routers.qb.rule=Host(`qbittorrent.${DOMAINNAME}`)
      - traefik.frontend.rule=Host:qbittorrent.${DOMAINNAME}
      - traefik.http.routers.qb.entrypoints=web
      - traefik.http.services.qb.loadbalancer.server.port=7503
        
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    networks:
      - discovery
    depends_on:                                                                              
      - qbittorrent 
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
    volumes:
      - /mnt/storage/config/radarr:/config
      - /mnt/storage/downloads:/downloads
      - /mnt/storage/media/Movies:/movies
    labels:
      - traefik.enable=true
      - traefik.http.routers.radarr.rule=Host(`radarr.${DOMAINNAME}`)
      - traefik.frontend.rule=Host:radarr.${DOMAINNAME}

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    networks:
      - discovery
    depends_on:                                                                              
      - qbittorrent 
    ports:
      - "8989:8989"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Copenhagen
    volumes:
      - /mnt/storage/config/sonarr:/config
      - /mnt/storage/downloads:/downloads
      - /mnt/storage/media/TV Shows:/tv
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr.rule=Host(`sonarr.${DOMAINNAME}`)
      - traefik.frontend.rule=Host:sonarr.${DOMAINNAME}

  jackett:
    image: linuxserver/jackett
    container_name: jackett
    networks:
      - discovery
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/Copenhagen
        - AUTO_UPDATE=true #optional
      #  - RUN_OPTS=#optional
    ports:
      - 9117:9117
    volumes:
        - /mnt/storage/config/jackett:/config
        - /mnt/storage/downloads:/downloads
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.jackett.rule=Host(`jackett.${DOMAINNAME}`)
      - traefik.frontend.rule=Host:jackett.${DOMAINNAME}

  plex:
    container_name: plex
    image: lscr.io/linuxserver/plex:latest
    restart: unless-stopped
    ports:
      - 32400:32400
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=Europe/Copenhagen
      - VERSION=docker
      - ADVERTISE_IP=http://plex.${DOMAINNAME}/
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/storage/config/plex:/config
      - /mnt/storage/transcode:/transcode
      - /mnt/storage/media/TV Shows:/data/TV Shows
      - /mnt/storage/media/Movies:/data/Movies
    labels:
      - traefik.enable=true
      - traefik.http.routers.plex.rule=Host(`plex.${DOMAINNAME}`)
      - traefik.frontend.rule=Host:plex.${DOMAINNAME}
      - traefik.http.services.plex.loadbalancer.server.port=32400

networks:
  # Discovery is manually created to avoid forcing any order of docker-compose stack creation (`docker network create discovery`)
  # allows other compose files to be seen by proxy
  # Not required if you aren't using multiple docker-compose files...
  discovery:
    external: true