[log]
  # DEBUG, PANIC, FATAL, ERROR, WARN, and INFO
  level = "DEBUG" # Should change this after setup

[api]
  dashboard = true
  debug = true
  insecure = false # If true, you can access dashboard on 8080 port (open 8080 first..)

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"
  exposedByDefault = false # traefik.enable=true is needed
  network = "app-net"

[entryPoints]
  [entryPoints.web]
    address = ":8000"

  [entryPoints.websecure]
    address = ":8443"

[certificatesResolvers.myresolver.acme]
  email = "hojland93@gmail.com"
  storage = "acme.json"
  # For testing, use staging server - uses production by default
  # caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
  [certificatesResolvers.myresolver.acme.httpChallenge]
    # Port 80 needs to be open
    entryPoint = "web"

[ping]
  entryPoint = "web"

[http]
  [http.routers]
     # Define a connection between requests and services
     [http.routers.to-dashboard]
      rule = "Host(`traefik.${DOMAIN}`)"
      service = "traefik"